### ISSUE TITLE
Union types not supported in PHP ^7.3

### ISSUE THREAD

**Issue by tdiam** [idleberg/php-wordpress-vite-assets#1]
### Description
Union types (like `array|string`) were introduced in PHP 8.0, so the package breaks in PHP `^7.3`.

### Steps to Reproduce

1. Copy the [README code](https://github.com/idleberg/php-wordpress-vite-assets#usage) to a WordPress codebase.
2. Run with PHP 7.x.

**Expected behavior:**

Runs properly.

**Actual behavior:**

`Fatal error: Uncaught Error: syntax error, unexpected '|', expecting variable (T_VARIABLE)`

### Versions

All versions.

**Comment by idleberg** [comment]
Thank you, I had no idea and followed my TypeScript habbits. I have removed the union types temporarily in v0.3.1 and plan to re-introduce them in November, when the minimum version will be bumped to PHP 8.0. Looking at the [supported versions](https://www.php.net/supported-versions.php), I will also bump the minimum version to PHP 7.4 in the next release.
