### ISSUE TITLE
Feature Request: Add a demo `vite.config.js` file that works with this class

### ISSUE THREAD

**Issue by DamChtlv** [idleberg/php-wordpress-vite-assets#16]
First of all, thanks for your work!

## Question
It seems complete _(except for the client not included when using just `vite` #15)_
Maybe it's related to the client or new version of vite _(v5+)_ but i can't make it work...
and maybe it's because of my **WP setup** or **vite config** so i'm wondering if that's the case.
More infos about the `vite.config.js` would be helpful :)

## Additionnal infos
**My WP setup**:
- **Server**: Docker WP environment using `.wp-env.json` _([@wordpress/env](https://github.com/WordPress/gutenberg/tree/trunk/packages/env))_ which i can access at `localhost:8888`
_(ex: `localhost:8888/wp-login.php`)_
- **Frontend**: Gutenberg _(using FSE / blocks, i'm not using any kind of JS frameworks)_
- **Theme**: my source assets are in `/src` and my build assets are generated in `/dist`

Here is a "minimalist" version of my `vite.config.js`:
```js
// vite.config.js

import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
	build: {
		minify: true,
		manifest: true,
		emptyOutDir: true,
		sourcemap: true,
		outDir: `dist/`,
		rollupOptions: {
			// overwrite default .html entry
			input: resolve(__dirname, 'src/index.js'),
		},
	},
	server: {
		host: true,
		strictPort: true,
		cors: true,
		port: 5173,
		hmr: {
			port: 5173,
			host: 'localhost',
		},
		proxy: {
			'/': {
				target: 'http://localhost:8888',
				changeOrigin: true,
				secure: false,
			},
		},
		watch: { usePolling: true },
	},
});
```

**Comment by idleberg** [comment]
I created this package primarily for use with SvelteKit, the config is pretty unspectacular.

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';

const config: UserConfig = {
	plugins: [sveltekit()],
};

export default config;
```

Also, I found some POCs for Svelte, Vue, and SolidJS on my computer. They only differ in the use of a different plugin. So no secret sauce involved, pretty basic.

The projects are fairly old, they still use Vite 3, but I've ran into some minor quirks with upgrading from Vite 4 to 5 in some other, unrelated problems. I will try and upgrade my apps and report back. Might take a while though!
