### ISSUE TITLE
Php 7.4 / 8.0 compatibility ?

### ISSUE THREAD

**Issue by gmirmand** [idleberg/php-wordpress-vite-assets#5]
Hi ! I get the following error

> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.21. in /var/www/html/<project>/vendor/composer/platform_check.php on line 24

Is there any way to get php 7.4 and/or 8.0 compatibility?

**Comment by idleberg** [comment]
I'm not sure this error is related to this package (see its [PHP dependency](https://github.com/idleberg/php-wordpress-vite-assets/blob/5ba03ff6f2c451e4b6fe88f72224f4eda0c946f6/composer.json#L26)). It sounds like you're using PHP v7.4.21 while *some* dependency requires v8.1 or higher.

**Comment by gmirmand** [comment]
Yes, my bad it was my fault
Just had to put

**`composer.json`**
```json
    "config": {
        "platform": {
            "php": "7.4.0"
        }
    }
```

Sorry for that, ty !
